<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TMG.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Humanizer.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\TMG.Contracts\\TMG.Contracts.csproj" />
  </ItemGroup>
</Project>
