using System.Text.Json;
using System.Text.Json.Serialization;

namespace TMG.WebAPI.Features.Payments.Webhooks.SafeHaven;

public sealed record SafeHavenWebhookRequest(
    [property: JsonPropertyName("type")] string Type,
    JsonElement Data,
    [property: JsonPropertyName("eventType")] string? EventType = null)
{
    [JsonIgnore]
    public string Event => string.IsNullOrWhiteSpace(EventType) ? Type : EventType;
}

public sealed record SafeHavenAccountCreditWebhookData(
    [property: JsonPropertyName("queued")] bool Queued,
    [property: JsonPropertyName("limitExceeded")] bool LimitExceeded,
    [property: JsonPropertyName("_id")] string Id,
    [property: JsonPropertyName("client")] string Client,
    [property: JsonPropertyName("account")] string Account,
    [property: JsonPropertyName("type")] string TransactionType,
    [property: JsonPropertyName("sessionId")] string SessionId,
    [property: JsonPropertyName("nameEnquiryReference")] string NameEnquiryReference,
    [property: JsonPropertyName("paymentReference")] string PaymentReference,
    [property: JsonPropertyName("mandateReference")] string? MandateReference,
    [property: JsonPropertyName("isReversed")] bool IsReversed,
    [property: JsonPropertyName("reversalReference")] string? ReversalReference,
    [property: JsonPropertyName("provider")] string Provider,
    [property: JsonPropertyName("providerChannel")] string ProviderChannel,
    [property: JsonPropertyName("providerChannelCode")] string ProviderChannelCode,
    [property: JsonPropertyName("destinationInstitutionCode")] string DestinationInstitutionCode,
    [property: JsonPropertyName("creditAccountName")] string CreditAccountName,
    [property: JsonPropertyName("creditAccountNumber")] string CreditAccountNumber,
    [property: JsonPropertyName("creditBankVerificationNumber")] string? CreditBankVerificationNumber,
    [property: JsonPropertyName("creditKYCLevel")] string CreditKycLevel,
    [property: JsonPropertyName("debitAccountName")] string DebitAccountName,
    [property: JsonPropertyName("debitAccountNumber")] string DebitAccountNumber,
    [property: JsonPropertyName("realDebitAccountName")] string RealDebitAccountName,
    [property: JsonPropertyName("realDebitAccountNumber")] string RealDebitAccountNumber,
    [property: JsonPropertyName("debitBankVerificationNumber")] string? DebitBankVerificationNumber,
    [property: JsonPropertyName("debitKYCLevel")] string DebitKycLevel,
    [property: JsonPropertyName("transactionLocation")] string? TransactionLocation,
    [property: JsonPropertyName("narration")] string? Narration,
    [property: JsonPropertyName("amount")] decimal Amount,
    [property: JsonPropertyName("fees")] decimal Fees,
    [property: JsonPropertyName("vat")] decimal Vat,
    [property: JsonPropertyName("stampDuty")] decimal StampDuty,
    [property: JsonPropertyName("responseCode")] string? ResponseCode,
    [property: JsonPropertyName("responseMessage")] string? ResponseMessage,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("isDeleted")] bool IsDeleted,
    [property: JsonPropertyName("createdAt")] DateTimeOffset CreatedAt,
    [property: JsonPropertyName("updatedAt")] DateTimeOffset UpdatedAt);

public sealed record SafeHavenAccountDebitWebhookData(
    [property: JsonPropertyName("queued")] bool Queued,
    [property: JsonPropertyName("limitExceeded")] bool LimitExceeded,
    [property: JsonPropertyName("_id")] string Id,
    [property: JsonPropertyName("client")] string Client,
    [property: JsonPropertyName("account")] string Account,
    [property: JsonPropertyName("type")] string TransactionType,
    [property: JsonPropertyName("sessionId")] string SessionId,
    [property: JsonPropertyName("nameEnquiryReference")] string NameEnquiryReference,
    [property: JsonPropertyName("paymentReference")] string PaymentReference,
    [property: JsonPropertyName("mandateReference")] string? MandateReference,
    [property: JsonPropertyName("isReversed")] bool IsReversed,
    [property: JsonPropertyName("reversalReference")] string? ReversalReference,
    [property: JsonPropertyName("provider")] string Provider,
    [property: JsonPropertyName("providerChannel")] string ProviderChannel,
    [property: JsonPropertyName("providerChannelCode")] string ProviderChannelCode,
    [property: JsonPropertyName("destinationInstitutionCode")] string DestinationInstitutionCode,
    [property: JsonPropertyName("creditAccountName")] string CreditAccountName,
    [property: JsonPropertyName("creditAccountNumber")] string CreditAccountNumber,
    [property: JsonPropertyName("creditBankVerificationNumber")] string? CreditBankVerificationNumber,
    [property: JsonPropertyName("creditKYCLevel")] string CreditKycLevel,
    [property: JsonPropertyName("debitAccountName")] string DebitAccountName,
    [property: JsonPropertyName("debitAccountNumber")] string DebitAccountNumber,
    [property: JsonPropertyName("debitBankVerificationNumber")] string? DebitBankVerificationNumber,
    [property: JsonPropertyName("debitKYCLevel")] string DebitKycLevel,
    [property: JsonPropertyName("transactionLocation")] string? TransactionLocation,
    [property: JsonPropertyName("narration")] string? Narration,
    [property: JsonPropertyName("amount")] decimal Amount,
    [property: JsonPropertyName("fees")] decimal Fees,
    [property: JsonPropertyName("vat")] decimal Vat,
    [property: JsonPropertyName("stampDuty")] decimal StampDuty,
    [property: JsonPropertyName("responseCode")] string? ResponseCode,
    [property: JsonPropertyName("responseMessage")] string? ResponseMessage,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("isDeleted")] bool IsDeleted,
    [property: JsonPropertyName("createdAt")] DateTimeOffset CreatedAt,
    [property: JsonPropertyName("createdBy")] string? CreatedBy,
    [property: JsonPropertyName("updatedAt")] DateTimeOffset UpdatedAt);

public sealed record SafeHavenVirtualAccountTransferWebhookData(
    [property: JsonPropertyName("_id")] string Id,
    [property: JsonPropertyName("client")] string Client,
    [property: JsonPropertyName("virtualAccount")] string VirtualAccount,
    [property: JsonPropertyName("sessionId")] string SessionId,
    [property: JsonPropertyName("nameEnquiryReference")] string NameEnquiryReference,
    [property: JsonPropertyName("paymentReference")] string PaymentReference,
    [property: JsonPropertyName("isReversed")] bool IsReversed,
    [property: JsonPropertyName("reversalReference")] string? ReversalReference,
    [property: JsonPropertyName("provider")] string Provider,
    [property: JsonPropertyName("providerChannel")] string ProviderChannel,
    [property: JsonPropertyName("providerChannelCode")] string ProviderChannelCode,
    [property: JsonPropertyName("destinationInstitutionCode")] string DestinationInstitutionCode,
    [property: JsonPropertyName("creditAccountName")] string CreditAccountName,
    [property: JsonPropertyName("creditAccountNumber")] string CreditAccountNumber,
    [property: JsonPropertyName("creditBankVerificationNumber")] string? CreditBankVerificationNumber,
    [property: JsonPropertyName("creditKYCLevel")] string CreditKycLevel,
    [property: JsonPropertyName("debitAccountName")] string DebitAccountName,
    [property: JsonPropertyName("debitAccountNumber")] string DebitAccountNumber,
    [property: JsonPropertyName("debitBankVerificationNumber")] string? DebitBankVerificationNumber,
    [property: JsonPropertyName("debitKYCLevel")] string DebitKycLevel,
    [property: JsonPropertyName("transactionLocation")] string? TransactionLocation,
    [property: JsonPropertyName("narration")] string? Narration,
    [property: JsonPropertyName("amount")] decimal Amount,
    [property: JsonPropertyName("fees")] decimal Fees,
    [property: JsonPropertyName("vat")] decimal Vat,
    [property: JsonPropertyName("stampDuty")] decimal StampDuty,
    [property: JsonPropertyName("responseCode")] string? ResponseCode,
    [property: JsonPropertyName("responseMessage")] string? ResponseMessage,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("isDeleted")] bool IsDeleted,
    [property: JsonPropertyName("createdAt")] DateTimeOffset CreatedAt,
    [property: JsonPropertyName("declinedAt")] DateTimeOffset? DeclinedAt,
    [property: JsonPropertyName("updatedAt")] DateTimeOffset UpdatedAt);
